matches/urls.py
from django.urls import path
from matches import views

urlpatterns = [
    path("schedule/", views.ScheduleView.as_view(), name="schedule"),
]

ranklists/urls.py
from django.urls import path

from ranklists import views

urlpatterns = [
    path("", views.RankListView.as_view(), name="ranklist"),
    path("gin/balance/", views.GinPointsMatchesView.as_view(), name="gin_total"),
    path("gin/users/", views.GinPointsUsersView.as_view(), name="gin_users"),
    path("gin/usages/", views.GinPointsNumberOfUsagesView.as_view(), name="gin_usages"),
    path(
        "detail/<int:pk>",
        views.RankilstUserPointsView.as_view(),
        name="ranklist_detail",
    ),
]

matches/models.py
import datetime
import uuid

from django.db import models
from django.utils import timezone

from events.models import EventMatchState, EventPhase, Team


class MatchManager(models.Manager):
    def get_matches_for_date(self, date=None, event=None):
        eval_date = timezone.now().date() if date is None else date
        start_time = datetime.datetime.combine(eval_date, datetime.time(0, 0, 1))
        final_time = datetime.datetime.combine(eval_date, datetime.time(23, 59, 59))
        qs = self.get_queryset().filter(match_start_time__gte=start_time, match_start_time__lte=final_time)
        if event is not None:
            qs = qs.filter(phase__event=event)
        return qs


class Match(models.Model):
    home = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="country_home")
    guest = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="country_guest")
    phase = models.ForeignKey(EventPhase, on_delete=models.PROTECT, related_name="match_phase")
    match_number = models.IntegerField()
    match_start_time = models.DateTimeField()
    uuid = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    created_on = models.DateTimeField(auto_now_add=True)
    edited_on = models.DateTimeField(auto_now=True)

    objects = MatchManager()

    def __str__(self):
        return_str = (
            f"мач {self.match_number} | "
            f'{self.home.name} - {self.guest.name} | {self.match_start_time.strftime("%d.%m.%Y - %H:%M")}'
        )
        return return_str

    class Meta:
        unique_together = (
            "home",
            "guest",
            "phase",
        )
        ordering = ["match_start_time"]


class MatchResult(models.Model):
    # !NB has post save signal - signals.py

    match = models.OneToOneField(Match, on_delete=models.CASCADE, related_name="match_result")
    match_state = models.ForeignKey(EventMatchState, on_delete=models.PROTECT)
    score_home = models.IntegerField(default=0)
    score_guest = models.IntegerField(default=0)
    score_after_penalties_home = models.IntegerField(default=0)
    score_after_penalties_guest = models.IntegerField(default=0)
    penalties = models.BooleanField(default=False)
    match_is_over = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    edited_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.match)

ranklists/models.py
from django.db import models

# Create your models here.

ranklists/views.py
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.db.models import Count, Sum
from django.views.generic import ListView, TemplateView

from matches.models import Match
from predictions.models import PredictionPoint, UserPrediction, UserScore


class RankListView(ListView):
    template_name = "ranklists/ranklist.html"
    model = UserScore
    context_object_name = "ranklist"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.order_by("-points")
        return queryset


class RankilstUserPointsView(ListView):
    model = UserPrediction
    template_name = "ranklists/ranklist-detail.html"
    context_object_name = "ranklist"
    user = None
    paginate_by = 4

    def get_queryset(self):
        self.user = get_user_model().objects.get(pk=self.kwargs["pk"])
        queryset = (
            UserPrediction.objects.filter(user=self.user, match__match_result__match_is_over=True)
            .order_by("-match__match_start_time")
            .select_related("match")
            .prefetch_related("match__match_result")
        )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context["username"] = self.user
        return context


class GinPointsMatchesView(TemplateView):
    template_name = "ranklists/gin/matches.html"

    def get_points_per_match(self):
        raw_data = list(
            PredictionPoint.objects.all()
            .order_by("-prediction__match__match_start_time")
            .values("prediction__match")
            .annotate(Sum("additional_points"))
        )
        result = {
            Match.objects.get(pk=item["prediction__match"]): item["additional_points__sum"] * -1 for item in raw_data
        }
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_balance = (
            PredictionPoint.objects.all().aggregate(Sum("additional_points")).get("additional_points__sum")
        ) or 0
        context["total_balance"] = total_balance * -1
        context["per_match"] = self.get_points_per_match()

        page_number = self.request.GET.get("page")
        paginator = Paginator(list(self.get_points_per_match().keys()), 10)
        page_obj = paginator.get_page(page_number)
        context["page_obj"] = page_obj
        return context


class GinPointsUsersView(TemplateView):
    template_name = "ranklists/gin/users.html"

    @staticmethod
    def get_data():
        qs = (
            PredictionPoint.objects.filter(additional_points__lt=0)
            .values("prediction__user")
            .annotate(Sum("additional_points"))
        )
        raw_data = list(qs)
        result_negative = {
            get_user_model().objects.get(pk=item["prediction__user"]): item["additional_points__sum"]
            for item in raw_data
        }

        qs = (
            PredictionPoint.objects.filter(additional_points__gt=0)
            .values("prediction__user")
            .annotate(Sum("additional_points"))
        )
        raw_data = list(qs)
        result_positive = {
            get_user_model().objects.get(pk=item["prediction__user"]): item["additional_points__sum"]
            for item in raw_data
        }

        result = {
            user: result_positive.get(user, 0) + result_negative.get(user, 0) for user in get_user_model().objects.all()
        }
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["per_user"] = self.get_data()
        return context


class GinPointsNumberOfUsagesView(TemplateView):
    template_name = "ranklists/gin/usages.html"

    @staticmethod
    def get_data():
        qs = (
            PredictionPoint.objects.annotate(Count("prediction__bet_points__apply_match_state"))
            .filter(
                prediction__bet_points__apply_match_state=True,
                prediction__bet_points__apply_match_state__count__gt=0,
            )
            .values("prediction__user")
            .annotate(Count("prediction__bet_points__apply_match_state"))
        )
        raw_data = list(qs)
        result_state = {
            get_user_model().objects.get(pk=item["prediction__user"]): item[
                "prediction__bet_points__apply_match_state__count"
            ]
            for item in raw_data
        }

        qs = (
            PredictionPoint.objects.annotate(Count("prediction__bet_points__apply_result"))
            .filter(
                prediction__bet_points__apply_result=True,
                prediction__bet_points__apply_result__count__gt=0,
            )
            .values("prediction__user")
            .annotate(Count("prediction__bet_points__apply_result"))
        )
        raw_data = list(qs)
        result_result = {
            get_user_model().objects.get(pk=item["prediction__user"]): item[
                "prediction__bet_points__apply_result__count"
            ]
            for item in raw_data
        }

        result = {
            user: result_state.get(user, 0) + result_result.get(user, 0)
            for user in get_user_model().objects.all()
            if user in result_result or user in result_state
        }
        result = {item: result[item] for item in sorted(result, key=lambda x: result[x], reverse=True)}
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["per_user"] = self.get_data()
        return context

ranklists/templates/ranklists/gin/base.html
{% extends 'base.html' %}
{% load static ranking_tags %}

{% block body_classes %}body-2{% endblock %}

{% block body_content %}
    <div class="inner_page_header">
        <div class="heading inner-ttl">АНГЕЛ-А</div>
    </div>
    <div class="inner-page-image">
        {% gin_is_happy as happy_check %}
        <img src="{% if happy_check %}{% static 'images/gin2.png' %}{% else %}{% static 'images/gin1.png' %}{% endif %}"
                class="image--round">
    </div>
    <div class="content-wrp">
        <div data-duration-in="300" data-duration-out="100" class="tabs w-tabs">
            <div class="tabs-menu w-tab-menu">
                <a href="{% url 'gin_total' %}"
                        class="tab-link w-inline-block w-tab-link {% block balance_active %}{% endblock %}">
                    <div class="tab-text">МАЧОВЕ</div>
                </a>
                <a href="{% url 'gin_users' %}"
                        class="tab-link w-inline-block w-tab-link {% block users_active %}{% endblock %}">
                    <div class="tab-text">ИГРАЧИ</div>
                </a>
                <a href="{% url 'gin_usages' %}"
                        class="tab-link w-inline-block w-tab-link {% block use_active %}{% endblock %}">
                    <div class="tab-text">ИЗПОЛЗВАЧИ</div>
                </a>
            </div>
            <div class="tabs-content w-tab-content">
                {% block gin_content %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

ranklists/templates/ranklists/gin/matches.html
{% extends 'ranklists/gin/base.html' %}
{% load custom_tags %}
{% block balance_active %}w--current{% endblock %}

{% block  gin_content %}
    <div class="form-txt">
        <div class="text-block histprylist bonus-list">
            <h1 class="color-primary--inverted">
                БАЛАНС: {{ total_balance }} точки
            </h1>
            <h3 class="color-primary--inverted mb20">
                {% if total_balance < 0 %}
                    АНГЕЛ-А е ГЛАДЕН!
                {% else %}
                    АНГЕЛ-А е сит.
                {% endif %}
            </h3>
            <h4 class="color-primary--inverted">Резултата по мачове</h4>
            <hr>
            {% if page_obj.object_list %}
                {% for match in page_obj.object_list %}
                    {% get_values_from_dictionary_tag per_match match as points %}
                    {% with match.match_result as match_result %}
                        <p>
                        <span class="color-primary--inverted {% if points > 0 %} color-positive{% endif %}">
                            От {% replace_str match '|' '' %}
                            {% if points > 0 %}
                                АНГЕЛ-А ВЗЕ
                            {% else %}
                                АНГЕЛ-А ДАДЕ
                            {% endif %}
                            {{ points|absolute_value }}
                            {% if points == 1 %}
                                точка
                            {% else %}
                                точки
                            {% endif %}
                        </span>
                            <br>
                            Завършил: {{ match_result.match_state.get_match_state_display }} |
                            {{ match_result.score_home }} : {{ match_result.score_guest }}
                            {% if match_result.penalties %}
                                ( {{ match_result.score_after_penalties_home }} :
                                {{ match_result.score_after_penalties_guest }} )
                            {% endif %}
                        </p>
                    {% endwith %}
                    <br>
                {% endfor %}
            {% else %}
                <p class="dummy--no__info">Към момента информацията е кът.</p>
            {% endif %}
        </div>
    </div>
    {% include 'main_app/components/paginator.html' %}
{% endblock %}

ranklists/templates/ranklists/gin/usages.html
{% extends 'ranklists/gin/base.html' %}
{% load custom_tags %}
{% block use_active %}w--current{% endblock %}

{% block  gin_content %}
    <div class="form-txt">
        <div class="text-block histprylist bonus-list">
            <h1 class="color-primary--inverted">КЛАСАЦИЯ</h1>
            <h5 class="color-primary--inverted">*Всяка оферта се брои!
                Ако си приел оферти за изход от двубоя и за краен резултат, то си приел оферти 2 пъти, нищо че е за един
                и същи мач.
            </h5>
            <hr>
            {% for user,points in per_user.items %}
                <p class="color-negative">
                    <strong>{{ user }}</strong> е приел мои оферти <strong>{{ points }}</strong> пъти
                </p>
            {% endfor %}
        </div>
    </div>
    {% include 'main_app/components/paginator.html' %}
{% endblock %}

ranklists/templates/ranklists/gin/users.html
{% extends 'ranklists/gin/base.html' %}
{% load custom_tags %}
{% block users_active %}w--current{% endblock %}

{% block  gin_content %}
    <div class="form-txt">
        <div class="text-block histprylist bonus-list">
            <h1 class="color-primary--inverted">КЛАСАЦИЯ</h1>
            <hr>
            {% for user,points in per_user.items %}

                {% if points > 0 %}
                    <p class="color-negative">
                        <strong>{{ user }}</strong> ми е ВЗЕЛ <strong>{{ points|absolute_value }}</strong> точки.
                        ГАДНЯР/КА!
                    </p>
                {% elif points < 0 %}
                    <p class="color-positive">
                        <strong>{{ user }}</strong> ми е ДАЛ <strong>{{ points|absolute_value }}</strong> точки.
                        ДОБРЯК/ЧКА!
                    </p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    {% include 'main_app/components/paginator.html' %}
{% endblock %}